"use strict"

try {
    let x = 10;
    //miFuncion();
    console.log(x);
} 
catch (error) {
    console.log(error);
}
finally{
    console.log("continuamos...");
}

